const questions = [
    {
      q: "Demo Question",
      a: "Demo Answer",
      imagepath : 'assets/images/questions/q1.png',
      audiopath : null,
      videopath : null,
      score : 0,
    },
    {
      q: "What is the capital of France?",
      a: "Paris",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "Which planet is known as the Red Planet?",
      a: "Mars",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "What is the largest mammal on Earth?",
      a: "Blue whale",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "Who wrote Romeo and Juliet?",
      a: "William Shakespeare",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "What is the main ingredient in guacamole?",
      a: "Avocado",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "What is the currency of Japan?",
      a: "Japanese yen",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "What is the tallest land animal?",
      a: "Giraffe",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "How many continents are there in the world?",
      a: "Seven",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "What is the chemical symbol for gold?",
      a: "Au",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    },
    {
      q: "Which country is commonly referred to as the 'Land of the Rising Sun'?",
      a: "Japan",
      imagepath : null,
      audiopath : null,
      videopath : null,
      score : 5,
    }
  ];

  export default questions;